"""empty message

Revision ID: 168f714a1153
Revises: a00ca29c2c6c
Create Date: 2025-02-11 11:03:49.165568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168f714a1153'
down_revision = 'a00ca29c2c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role_table', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
