"""empty message

Revision ID: 23498ab43b92
Revises: 7bbae6d2bc12
Create Date: 2025-05-14 17:03:45.213586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23498ab43b92'
down_revision = '7bbae6d2bc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('salary_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['salary_id'], ['salaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('requirements', sa.String(length=800), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role_table')
    op.drop_table('worker_table')
    op.drop_table('department_table')
    op.drop_table('offer_table')
    op.drop_table('salary_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('salary_table_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('gross_salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='salary_table_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('offer_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='offer_table_pkey')
    )
    op.create_table('department_table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('department_table_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=800), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='department_table_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('worker_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('birthdate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('profile_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_table.id'], name='worker_table_department_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], name='worker_table_role_id_fkey'),
    sa.ForeignKeyConstraint(['salary_id'], ['salary_table.id'], name='worker_table_salary_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='worker_table_pkey'),
    sa.UniqueConstraint('dni', name='worker_table_dni_key'),
    sa.UniqueConstraint('email', name='worker_table_email_key')
    )
    op.create_table('role_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_table.id'], name='role_table_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='role_table_pkey')
    )
    op.drop_table('offers')
    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('salaries')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
