"""empty message

Revision ID: 344951d10cd8
Revises: 651a9b34f758
Create Date: 2025-02-11 11:07:21.647638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344951d10cd8'
down_revision = '651a9b34f758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_table', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'salary_table', ['salary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
