"""empty message

Revision ID: 4382a84b1f32
Revises: 92987d1c2716
Create Date: 2025-02-11 09:55:47.049322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4382a84b1f32'
down_revision = '92987d1c2716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint('department_table_boss_id_fkey', type_='foreignkey')
        batch_op.drop_column('boss_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('department_table_boss_id_fkey', 'worker_table', ['boss_id'], ['id'])

    # ### end Alembic commands ###
