"""empty message

Revision ID: 4a1fd5cf798f
Revises: 7b15466f3838
Create Date: 2025-02-10 20:03:57.811927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1fd5cf798f'
down_revision = '7b15466f3838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'worker_table', ['boss_id'], ['id'])

    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role_table', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'salary_table', ['salary_id'], ['id'])

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])

    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salary_table', ['salary_id'], ['id'])
        batch_op.drop_column('lastname')
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('level',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=800),
               existing_nullable=False)
        batch_op.drop_column('department_id')

    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('boss_id')

    # ### end Alembic commands ###
