"""empty message

Revision ID: 5d55a9f12a60
Revises: cff1749f42c6
Create Date: 2025-08-13 19:36:28.625532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d55a9f12a60'
down_revision = 'cff1749f42c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_employee_id_fkey'), 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###
