"""empty message

Revision ID: 651a9b34f758
Revises: 168f714a1153
Create Date: 2025-02-11 11:06:31.789669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651a9b34f758'
down_revision = '168f714a1153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
