"""empty message

Revision ID: 6ae67b082bb4
Revises: 78bbd1e557d5
Create Date: 2025-02-11 09:45:28.980430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae67b082bb4'
down_revision = '78bbd1e557d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint('department_table_boss_id_fkey', type_='foreignkey')
        batch_op.drop_column('boss_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('department_table_boss_id_fkey', 'worker_table', ['boss_id'], ['id'])

    # ### end Alembic commands ###
