"""empty message

Revision ID: 6ee6b3f359eb
Revises: 344951d10cd8
Create Date: 2025-02-11 11:21:56.475384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee6b3f359eb'
down_revision = '344951d10cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_table_pkey')
    )
    # ### end Alembic commands ###
