"""empty message

Revision ID: 78bbd1e557d5
Revises: 4a1fd5cf798f
Create Date: 2025-02-10 20:19:53.981761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bbd1e557d5'
down_revision = '4a1fd5cf798f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.drop_constraint('offer_table_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('offer_table_department_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('offer_table_salary_id_fkey', type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('salary_id')

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.drop_constraint('role_table_department_id_fkey', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.drop_constraint('worker_table_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('worker_table_salary_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_column('salary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('worker_table_salary_id_fkey', 'salary_table', ['salary_id'], ['id'])
        batch_op.create_foreign_key('worker_table_role_id_fkey', 'role_table', ['role_id'], ['id'])

    with op.batch_alter_table('role_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('role_table_department_id_fkey', 'department_table', ['department_id'], ['id'])

    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('offer_table_salary_id_fkey', 'salary_table', ['salary_id'], ['id'])
        batch_op.create_foreign_key('offer_table_department_id_fkey', 'department_table', ['department_id'], ['id'])
        batch_op.create_foreign_key('offer_table_role_id_fkey', 'role_table', ['role_id'], ['id'])

    # ### end Alembic commands ###
