"""empty message

Revision ID: 914522da2a6b
Revises: db65b58f0a47
Create Date: 2025-02-11 10:33:42.861650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914522da2a6b'
down_revision = 'db65b58f0a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.alter_column('boss_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.alter_column('boss_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
