"""empty message

Revision ID: 9e4d0c264857
Revises: 0882bfb9253a
Create Date: 2025-02-18 16:39:30.342891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4d0c264857'
down_revision = '0882bfb9253a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint('department_table_boss_id_fkey', type_='foreignkey')
        batch_op.drop_column('boss_id')

    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.drop_constraint('offer_table_salary_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('offer_table_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('offer_table_department_id_fkey', type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('salary_id')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('offer_table_department_id_fkey', 'department_table', ['department_id'], ['id'])
        batch_op.create_foreign_key('offer_table_role_id_fkey', 'role_table', ['role_id'], ['id'])
        batch_op.create_foreign_key('offer_table_salary_id_fkey', 'salary_table', ['salary_id'], ['id'])

    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('department_table_boss_id_fkey', 'worker_table', ['boss_id'], ['id'])

    # ### end Alembic commands ###
