"""empty message

Revision ID: a00ca29c2c6c
Revises: 863d56194948
Create Date: 2025-02-11 11:00:57.136144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00ca29c2c6c'
down_revision = '863d56194948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salary_table', ['salary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')

    # ### end Alembic commands ###
