"""empty message

Revision ID: a9f15ee195a8
Revises: 9859f1478b38
Create Date: 2025-02-21 18:53:27.565815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f15ee195a8'
down_revision = '9859f1478b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_table', schema=None) as batch_op:
        batch_op.alter_column('gross_salary',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_table', schema=None) as batch_op:
        batch_op.alter_column('gross_salary',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
