"""empty message

Revision ID: b0fc82a76e94
Revises: 
Create Date: 2025-02-24 09:21:13.147847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fc82a76e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('requirements', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('salary_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_table.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], ),
    sa.ForeignKeyConstraint(['salary_id'], ['salary_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_table')
    op.drop_table('role_table')
    op.drop_table('salary_table')
    op.drop_table('offer_table')
    op.drop_table('department_table')
    # ### end Alembic commands ###
