"""empty message

Revision ID: bf0ac82a922a
Revises: b0530e4d467a
Create Date: 2025-02-13 09:26:59.349548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0ac82a922a'
down_revision = 'b0530e4d467a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'worker_table', ['boss_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('boss_id')

    # ### end Alembic commands ###
