"""empty message

Revision ID: db65b58f0a47
Revises: 0dc2cd92e09b
Create Date: 2025-02-11 10:20:47.517179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db65b58f0a47'
down_revision = '0dc2cd92e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'worker_table', ['boss_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('boss_id')

    # ### end Alembic commands ###
