"""empty message

Revision ID: ede012112d4d
Revises: a68be6c13864
Create Date: 2025-02-10 16:07:47.222434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede012112d4d'
down_revision = 'a68be6c13864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('requirements', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('level', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('sub_date', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('worker')
    op.drop_table('offer')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('dni', name='user_dni_key'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('offer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='offer_pkey')
    )
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('experience', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='worker_pkey'),
    sa.UniqueConstraint('dni', name='worker_dni_key'),
    sa.UniqueConstraint('email', name='worker_email_key')
    )
    op.drop_table('worker_table')
    op.drop_table('user_table')
    op.drop_table('salary_table')
    op.drop_table('role_table')
    op.drop_table('offer_table')
    op.drop_table('department_table')
    # ### end Alembic commands ###
