"""empty message

Revision ID: ef836d099173
Revises: cc79819730c7
Create Date: 2025-02-11 10:57:15.274876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef836d099173'
down_revision = 'cc79819730c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salary_table', ['salary_id'], ['id'])
        batch_op.create_foreign_key(None, 'role_table', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])

    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role_table', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('offer_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
